{{ if not .Values.appKey.useExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ferritecms.fullname" . }}-app-key
  labels:
    {{- include "ferritecms.labels" . | nindent 4 }}
type: Opaque
data:
  key: {{ .Values.appKey.key | b64enc | quote }}
{{- end }}
