{{ if and (not .Values.oauth.authentik.useExistingSecret) .Values.oauth.authentik.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ferritecms.fullname" . }}-authentik-oauth-credentials
  labels:
    {{- include "ferritecms.labels" . | nindent 4 }}
type: Opaque
data:
  client-id: {{ .Values.oauth.authentik.clientId | b64enc | quote }}
  client-secret: {{ .Values.oauth.authentik.clientSecret | b64enc | quote }}
{{ end }}
