{{ if and .Values.initialAdminUser.enabled (not .Values.initialAdminUser.useExistingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ferritecms.fullname" . }}-initial-admin-user-credentials
  labels:
    {{- include "ferritecms.labels" . | nindent 4 }}
type: Opaque
data:
  email: {{ .Values.initialAdminUser.email | b64enc | quote }}
  name: {{ .Values.initialAdminUser.name | b64enc | quote }}
  username: {{ .Values.initialAdminUser.username | b64enc | quote }}
  password: {{ .Values.initialAdminUser.password | b64enc | quote }}
{{ end }}
