{{ if .Values.queueWorker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ferritecms.fullname" . }}-queue-worker
  labels:
    {{- include "ferritecms.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.queueWorker.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ferritecms.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ferritecms.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ferritecms.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: storage-volume
          {{ if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{ else }}{{ include "ferritecms.fullname" . }}-pvc{{ end }}
          {{ else }}
          emptyDir: {}
          {{ end }}
      containers:
        - name: {{ .Chart.Name }}-queue-worker
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["php", "artisan", "queue:work", "--tries=3", "--timeout=90"]
          volumeMounts:
            - name: storage-volume
              mountPath: /var/www/html/storage/app
          envFrom:
          - configMapRef:
              name: {{ include "ferritecms.fullname" . }}-config
          env:
            {{ include "ferritecms.commonEnvVars" . | nindent 10 }}
          ports:
          livenessProbe:
            exec:
              command:
              - pgrep
              - php
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
              - pgrep
              - php
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{ end }}